version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Holiday"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/RomanNumbers"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/TusLibros"
    schedule:
      interval: "weekly"

