name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.203

    - name: Install dependencies
      run: |
           dotnet restore TusLibros

    - name: Install tools
      run: dotnet tool install --global coverlet.console

    - name: Build Release
      run: |
           for s in TusLibros; do
               dotnet build --configuration Release --no-restore $s
           done

    - name: Build Debug
      run: |
           for s in TusLibros; do
               dotnet build --configuration Debug --no-restore $s
           done

    - name: Testing
      run: |
           coverlet TusLibros.Core.UnitTests/bin/Debug/netcoreapp2.2/TusLibros.Core.UnitTests.dll --target "dotnet" --targetargs "test TusLibros.Core.UnitTests/TusLibros.Core.UnitTests.csproj --no-build --verbosity quiet" --format OpenCover --output TusLibros.core.coverage.xml
           coverlet TusLibros.API.UnitTests/bin/Debug/netcoreapp2.2/TusLibros.API.UnitTests.dll --target "dotnet" --targetargs "test TusLibros.API.UnitTests/TusLibros.API.UnitTests.csproj --no-build --verbosity quiet" --format OpenCover --output TusLibros.api.coverage.xml --exclude "[TusLibros.Core]*"

    - name: Upload
      run: bash <(curl -s https://codecov.io/bash)
